[book]
authors = ["Natesh Narain"]
language = "en"
multilingual = false
src = "src"
title = "Kratos"

[preprocessor.file-search]
files = [
    {alias = "schematic", path = "../hardware/kratos/out/design/kratos-schematic.pdf"},
    {alias = "ibom",      path = "../hardware/kratos/out/html/kratos-ibom.html"}
]
